[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Gear Team", email = "inigo@berkeley.edu"},
]
includes = [
    "src",
]
dependencies = [
    "click>=8.1.3",
    "sympy>=1.11",
    "numpy>=1.23.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=2.20.0",
    "pre-commit-hooks>=4.3.0",
    "black>=22.6.0",
    "flake8>=5.0.4",
    "isort>=5.10.1",
    "autoflake>=1.4",
    "mypy>=0.971",
    "docformatter>=1.5.0",
    "pep8-naming>=0.13.2",
    "pytest>=7.1.2",
    "pyupgrade>=2.37.3",
    "sphinx>=5.1.1",
    "sphinx-autobuild>=2021.3.14",
]

[tool.pdm.scripts]
conda-create = "pdm venv create --with conda"
conda-activate = "conda activate ./.venv"
conda-install = "conda env update --file environment.yml --prune"
gear = "gear.gear:main"

[tool.setuptools]

[tool.isort]

profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
mypy_path = "cps_design"
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true